services:

  db:
    image: mysql:8.0
    container_name: homegym-db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: homegym
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      # Monta qui la cartella locale ./db_init che contiene file .sql da eseguire all'init
      - ./db_init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    container_name: homegym-mongo
    environment:
      MONGO_INITDB_DATABASE: homegym_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  app:
    build: .
    image: homegym-app:latest
    container_name: homegym-app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - mongo
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: homegym
      DB_USER: root
      DB_PASSWORD: example
      DB_MAX_ACTIVE: 30
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB: homegym_mongo
    volumes:
      - ./logs:/usr/local/tomcat/logs
    restart: unless-stopped

  adminer:
    image: adminer:latest
    container_name: homegym-adminer
    ports:
      - "8081:8080"
    restart: unless-stopped

volumes:
  db_data:
  mongo_data:
